lib/portability.h: Do not declare _POSIX_C_SOURCE and _XOPEN_SOURCE on OS X.
When _POSIX_C_SOURCE 200809L or _XOPEN_SOURCE 600 is defined
the compilation on OS X 10.6 is failing with the following errors:

toys/chroot.c: In function ‘chroot_main’:
toys/chroot.c:25: warning: implicit declaration of function ‘chroot’
toys/hostname.c: In function ‘hostname_main’:
toys/hostname.c:26: warning: implicit declaration of function ‘sethostname’
toys/ls.c: In function ‘do_ls’:
toys/ls.c:67: warning: implicit declaration of function ‘scandir’
toys/ls.c:67: error: ‘alphasort’ undeclared (first use in this function)
toys/ls.c:67: error: (Each undeclared identifier is reported only once
toys/ls.c:67: error: for each function it appears in.)
toys/ls.c:162: warning: implicit declaration of function ‘major’
toys/ls.c:162: warning: implicit declaration of function ‘minor’
toys/mknod.c: In function ‘mknod_main’:
toys/mknod.c:48: warning: implicit declaration of function ‘makedev’
toys/oneit.c: In function ‘oneit_main’:
toys/oneit.c:67: warning: implicit declaration of function ‘reboot’